install.packages("dplyr")
install.packages("ggplot2")
install.packages("grid")
install.packages("corrplot")
install.packages("caret")
install.packages("tidyverse")
install.packages("tidyr")
install.packages("plyr")
install.packages("splitstackshape")
library(dplyr)
library(ggplot2)
library(grid)
library(corrplot)
library(caret)
library(tidyverse)
library(tidyr)
library(plyr)
library(splitstackshape)
source("/Users/welcome/Downloads/BI_active_learning/cleaning_R.R")

source("/Users/welcome/Downloads/BI_active_learning/analysis_R.R")

source("/Users/welcome/Downloads/BI_active_learning/regression_R.R")

cleaning()
analysis()
regression()

